//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_META
    {
        public CAT_META()
        {
            this.T_PLANEDUCACIONFORMAL = new HashSet<T_PLANEDUCACIONFORMAL>();
        }
    
        public int I_IDMETA { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<T_PLANEDUCACIONFORMAL> T_PLANEDUCACIONFORMAL { get; set; }
    }
}
