//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPODISCAPACIDAD
    {
        public CAT_TIPODISCAPACIDAD()
        {
            this.CAT_DISCAPACIDAD = new HashSet<CAT_DISCAPACIDAD>();
        }
    
        public int I_IDTIPODISCAPACIDAD { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<CAT_DISCAPACIDAD> CAT_DISCAPACIDAD { get; set; }
    }
}
