//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_DISTRITO
    {
        public CAT_DISTRITO()
        {
            this.CAT_PERSONA = new HashSet<CAT_PERSONA>();
            this.T_GRUPO = new HashSet<T_GRUPO>();
            this.T_LOCALIZACIONPARTICIPANTE = new HashSet<T_LOCALIZACIONPARTICIPANTE>();
            this.T_LOCALIZACIONPARTICIPANTE1 = new HashSet<T_LOCALIZACIONPARTICIPANTE>();
        }
    
        public int I_IDDISTRITO { get; set; }
        public Nullable<int> I_IDCANTON { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual CAT_CANTON CAT_CANTON { get; set; }
        public virtual ICollection<CAT_PERSONA> CAT_PERSONA { get; set; }
        public virtual ICollection<T_GRUPO> T_GRUPO { get; set; }
        public virtual ICollection<T_LOCALIZACIONPARTICIPANTE> T_LOCALIZACIONPARTICIPANTE { get; set; }
        public virtual ICollection<T_LOCALIZACIONPARTICIPANTE> T_LOCALIZACIONPARTICIPANTE1 { get; set; }
    }
}
