//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPOEDUCACIONBASICA
    {
        public CAT_TIPOEDUCACIONBASICA()
        {
            this.CAT_TIPOEDUCACIONBASICA1 = new HashSet<CAT_TIPOEDUCACIONBASICA>();
            this.T_PARTICIPANTEEDUCACIONFORMAL = new HashSet<T_PARTICIPANTEEDUCACIONFORMAL>();
        }
    
        public int I_IDTIPOEDUCACIONBASICA { get; set; }
        public Nullable<int> CAT_I_IDTIPOEDUCACIONBASICA { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<CAT_TIPOEDUCACIONBASICA> CAT_TIPOEDUCACIONBASICA1 { get; set; }
        public virtual CAT_TIPOEDUCACIONBASICA CAT_TIPOEDUCACIONBASICA2 { get; set; }
        public virtual ICollection<T_PARTICIPANTEEDUCACIONFORMAL> T_PARTICIPANTEEDUCACIONFORMAL { get; set; }
    }
}
