//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PERSONA
    {
        public int I_IDPERSONA { get; set; }
        public int I_IDTIPOIDENTIFICACION { get; set; }
        public Nullable<int> I_IDSEXO { get; set; }
        public Nullable<int> I_IDESTADOCIVIL { get; set; }
        public Nullable<int> I_IDREGION { get; set; }
        public Nullable<int> I_IDPROVINCIA { get; set; }
        public Nullable<int> I_IDCANTON { get; set; }
        public Nullable<int> I_IDDISTRITO { get; set; }
        public Nullable<int> I_IDCOMUNIDAD { get; set; }
        public Nullable<int> I_IDETNIA { get; set; }
        public Nullable<int> I_IDNACIONALIDAD { get; set; }
        public string VC_IDENTIFICACION { get; set; }
        public Nullable<System.DateTime> DT_IDENTIFICACIONVENCIMIENTO { get; set; }
        public string VC_NOMBRE { get; set; }
        public string VC_PRIMERAPELLIDO { get; set; }
        public string VC_SEGUNDOAPELLIDO { get; set; }
        public Nullable<System.DateTime> DT_FECHANACIMIENTO { get; set; }
        public string VC_CONOCIDOCOMO { get; set; }
        public string VC_OBSERVACIONESESTADOCIVIL { get; set; }
    }
}
