//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_RESPUESTACORTA
    {
        public CAT_RESPUESTACORTA()
        {
            this.T_PARTICIPANTEVIVIENDA = new HashSet<T_PARTICIPANTEVIVIENDA>();
            this.T_PARTICIPANTEVIVIENDA1 = new HashSet<T_PARTICIPANTEVIVIENDA>();
        }
    
        public int I_IDRESPUESTACORTA { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<T_PARTICIPANTEVIVIENDA> T_PARTICIPANTEVIVIENDA { get; set; }
        public virtual ICollection<T_PARTICIPANTEVIVIENDA> T_PARTICIPANTEVIVIENDA1 { get; set; }
    }
}
