//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PROGRAMA
    {
        public CAT_PROGRAMA()
        {
            this.T_PROGRAMAPERSONA = new HashSet<T_PROGRAMAPERSONA>();
        }
    
        public int I_IDPROGRAMA { get; set; }
        public string VC_DESCIPCION { get; set; }
    
        public virtual ICollection<T_PROGRAMAPERSONA> T_PROGRAMAPERSONA { get; set; }
    }
}
