//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPOASISTENCIA
    {
        public CAT_TIPOASISTENCIA()
        {
            this.T_ASISTENCIA = new HashSet<T_ASISTENCIA>();
        }
    
        public int I_IDTIPOASISTENCIA { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<T_ASISTENCIA> T_ASISTENCIA { get; set; }
    }
}
