//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PENSIONAPOYO
    {
        public CAT_PENSIONAPOYO()
        {
            this.T_INTEGRANTEPENSIONAPOYO = new HashSet<T_INTEGRANTEPENSIONAPOYO>();
        }
    
        public int I_IDPENSIONAPOYO { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<T_INTEGRANTEPENSIONAPOYO> T_INTEGRANTEPENSIONAPOYO { get; set; }
    }
}
