//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_UTILIDADESTUDIO
    {
        public CAT_UTILIDADESTUDIO()
        {
            this.T_PARTICIPANTEFORMACIONTECNICA = new HashSet<T_PARTICIPANTEFORMACIONTECNICA>();
        }
    
        public int I_IDUTILIDADESTUDIO { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<T_PARTICIPANTEFORMACIONTECNICA> T_PARTICIPANTEFORMACIONTECNICA { get; set; }
    }
}
