//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_PERFIL
    {
        public SEG_PERFIL()
        {
            this.SEG_USUARIO = new HashSet<SEG_USUARIO>();
            this.SEG_OPCIONSISTEMA = new HashSet<SEG_OPCIONSISTEMA>();
        }
    
        public int I_IDPERFIL { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<SEG_USUARIO> SEG_USUARIO { get; set; }
        public virtual ICollection<SEG_OPCIONSISTEMA> SEG_OPCIONSISTEMA { get; set; }
    }
}
