//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_USUARIO
    {
        public int I_IDUSUARIO { get; set; }
        public int I_IDPERSONA { get; set; }
        public int I_IDPERFIL { get; set; }
        public string VC_LOGIN { get; set; }
        public string VC_CONTRASENNA { get; set; }
    }
}
