//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ARCHIVOGRUPO
    {
        public int I_IDARCHIVOGRUPO { get; set; }
        public Nullable<int> I_IDGRUPO { get; set; }
        public string VC_URLARCHIVO { get; set; }
    
        public virtual T_GRUPO T_GRUPO { get; set; }
    }
}
