//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASISTENCIA
    {
        public int I_IDGRUPO { get; set; }
        public int I_IDTIPOASISTENCIA { get; set; }
        public int I_IDPARTICIPANTE { get; set; }
        public System.DateTime DT_FECHA { get; set; }
        public Nullable<bool> B_FECHAALTERNATIVA { get; set; }
    
        public virtual CAT_TIPOASISTENCIA CAT_TIPOASISTENCIA { get; set; }
        public virtual T_GRUPO T_GRUPO { get; set; }
        public virtual T_PARTICIPANTE T_PARTICIPANTE { get; set; }
    }
}
