//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BITACORA
    {
        public int I_IDBITACORA { get; set; }
        public Nullable<int> I_IDUSUARIO { get; set; }
        public Nullable<int> I_IDEVENTOBITACORA { get; set; }
        public System.DateTime DT_FECHA { get; set; }
    
        public virtual SEG_USUARIO SEG_USUARIO { get; set; }
        public virtual T_EVENTOBITACORA T_EVENTOBITACORA { get; set; }
    }
}
