//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GRUPO
    {
        public int I_IDGRUPO { get; set; }
        public int I_IDTIPOCURSO { get; set; }
        public string VC_NUMEROGRUPO { get; set; }
        public int I_IDREGION { get; set; }
        public Nullable<int> I_IDCANTON { get; set; }
        public Nullable<int> I_IDDISTRITO { get; set; }
        public int I_IDCOMUNIDAD { get; set; }
        public int I_IDTIPOLUGARREUNION { get; set; }
        public int I_IDCONDICIONLUGAR { get; set; }
        public int I_IDSITUACION { get; set; }
        public int I_IDRESPONSABLE { get; set; }
        public int I_IDTIPOPOBLACION { get; set; }
        public int I_IDFACILITADOR { get; set; }
        public Nullable<double> F_MONTOMENSUAL { get; set; }
        public string VC_OBSERVACIONES { get; set; }
        public string VC_METODOLOGIA { get; set; }
        public string VC_RESPUESTAGRUPO { get; set; }
        public int I_SESIONES { get; set; }
        public System.DateTime DT_FECHAINICIO { get; set; }
        public System.DateTime DT_FECHAFIN { get; set; }
        public System.DateTime DT_FECHAREALINICIO { get; set; }
        public System.DateTime DT_FECHAREALFIN { get; set; }
        public string VC_MOTIVOCAMBIOFECHA { get; set; }
    }
}
