//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HORARIOGRUPO
    {
        public int I_IDGRUPO { get; set; }
        public int I_IDDIA { get; set; }
        public Nullable<System.TimeSpan> T_HORAINICIO { get; set; }
        public Nullable<System.TimeSpan> T_HORAFIN { get; set; }
    }
}
