//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INTEGRANTEGRUPOFAMILIAR
    {
        public int I_IDINTEGRANTE { get; set; }
        public int I_IDPERSONA { get; set; }
        public int I_IDPARTICIPANTE { get; set; }
        public Nullable<int> I_IDPARENTESCO { get; set; }
        public Nullable<bool> B_TIENEEMPLEO { get; set; }
        public Nullable<int> I_IDOCUPACION { get; set; }
        public Nullable<bool> B_JEFEHOGAR { get; set; }
        public Nullable<int> I_IDLUGARTRABAJO { get; set; }
        public Nullable<int> I_IDTIPOINGRESOMONETARIO { get; set; }
        public Nullable<int> I_IDTIPOSEGURO { get; set; }
        public string VC_LUGARTRABAJO { get; set; }
        public Nullable<double> F_INGRESO { get; set; }
        public Nullable<double> F_MONTOAYUDAHOGAR { get; set; }
        public Nullable<bool> B_DEPENDEDEPARTICIPANTE { get; set; }
        public string VC_OBSERVACIONES { get; set; }
        public Nullable<bool> B_ESASEGURADO { get; set; }
    }
}
