//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PARTICIPANTEEDUCACIONFORMAL
    {
        public int I_IDEDUCACIONFORMAL { get; set; }
        public int I_IDPARTICIPANTE { get; set; }
        public Nullable<int> I_IDNIVELLECTURA { get; set; }
        public Nullable<int> I_IDNIVELESCRITURA { get; set; }
        public Nullable<int> I_IDTIPOEDUCACIONBASICA { get; set; }
        public Nullable<int> I_IDULTIMONIVELEDUCACIONBASICA { get; set; }
        public Nullable<int> I_IDTITULONIVELBASICO { get; set; }
        public Nullable<int> I_IDESPECIALIDADEDUCACIONBASICA { get; set; }
        public Nullable<int> I_IDTIPOEDUCACIONSUPERIOR { get; set; }
        public Nullable<int> I_IDULTIMONIVELEDUCACIONSUPER { get; set; }
        public Nullable<int> I_IDTITULONIVELSUPERIOR { get; set; }
        public Nullable<int> I_IDESPECIALIDADEDUCACIONSUPERIOR { get; set; }
        public Nullable<int> I_ANNOSEDUCACION { get; set; }
        public Nullable<bool> B_ESTUDIAACTUALMENTE { get; set; }
        public Nullable<int> I_IDINSTITUCIONEDUCATIVAACTUAL { get; set; }
        public Nullable<int> I_IDESPECIALIDADEDUCATIVAACTUAL { get; set; }
        public Nullable<int> I_IDTIPOHORARIOACTUAL { get; set; }
        public Nullable<int> I_IDMOTIVONOESTUDIA { get; set; }
    }
}
