//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PARTICIPANTEFORMACIONTECNICA
    {
        public int I_IDESTUDIOTECNICO { get; set; }
        public int I_IDPARTICIPANTE { get; set; }
        public string VC_INSTITUCION { get; set; }
        public int I_IDUTILIDADESTUDIO { get; set; }
        public Nullable<int> I_ANNOCONCLUCION { get; set; }
        public string VC_NOMBRECURSO { get; set; }
    }
}
