//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PARTICIPANTE
    {
        public int I_IDPARTICIPANTE { get; set; }
        public Nullable<int> I_IDGRUPO { get; set; }
        public string VC_NUMEROINGRESO { get; set; }
        public Nullable<int> I_IDPERSONA { get; set; }
        public Nullable<System.DateTime> DT_FECHAINICIO { get; set; }
        public Nullable<int> I_IDMEDIOINFORMACION { get; set; }
        public Nullable<int> I_IDREFERENCIA { get; set; }
        public int I_IDESTADO { get; set; }
        public string VC_TELEFONOMOVIL { get; set; }
        public string VC_TELEFONORESIDENCIA { get; set; }
        public string VC_PERSONACONFIANZA { get; set; }
        public string VC_CORREOELECTRONICO { get; set; }
        public Nullable<bool> B_JEFAHOGAR { get; set; }
        public string VC_JEFEHOGAR { get; set; }
        public Nullable<int> I_IDPUEBLOINDIGENA { get; set; }
        public Nullable<int> I_IDETNIA { get; set; }
    }
}
