//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PARTICIPANTECONDICIONESVIDA
    {
        public int I_ID_CONDICIONVIDA { get; set; }
        public Nullable<int> I_IDRIESGO { get; set; }
        public Nullable<int> I_IDPARTICIPANTE { get; set; }
        public bool B_ACCESOVIAPUBLICA { get; set; }
        public bool B_ACCESOTRANSPORTEPUBLICO { get; set; }
    
        public virtual CAT_RIESGOVIVIENDA CAT_RIESGOVIVIENDA { get; set; }
        public virtual T_PARTICIPANTE T_PARTICIPANTE { get; set; }
    }
}
