//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PLANPROYECTOPRODUCTIVO
    {
        public int I_IDPLANPROYECTOPRODUCTIVO { get; set; }
        public Nullable<int> I_IDPARTICIPANTE { get; set; }
        public Nullable<bool> B_RECIBIOAPOYO { get; set; }
        public string VC_DESCRIPCION { get; set; }
        public Nullable<int> I_ANNOPROYECTO { get; set; }
        public string VC_ESTADOPROYECTO { get; set; }
        public string VC_RECURSOSCUMPLIRINTERES { get; set; }
        public Nullable<int> I_IDRECURSOCUMPLIRINTERES { get; set; }
        public Nullable<int> I_IDINSTITUCIONCUMPLIRINTERES { get; set; }
        public Nullable<int> I_PRIORIDAD { get; set; }
    }
}
