//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROGRAMAPERSONA
    {
        public int I_IDPROGRAMA { get; set; }
        public int I_IDPERSONA { get; set; }
        public int I_ANNO { get; set; }
    
        public virtual CAT_PROGRAMA CAT_PROGRAMA { get; set; }
    }
}
