//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sipamu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SEGUIMIENTOPLANVIDA
    {
        public int I_IDSEGUIMIENTOPLANVIDA { get; set; }
        public int I_IDPARTICIPANTE { get; set; }
        public int I_IDTIPOPLANVIDA { get; set; }
        public Nullable<int> I_IDVALORACIONAPOYO { get; set; }
        public Nullable<int> I_IDTRAMITADOR { get; set; }
        public string VC_DESCRIPCION { get; set; }
        public Nullable<System.DateTime> DT_FECHA { get; set; }
        public string VC_OBSERVACION { get; set; }
        public string VC_TIPOAPOYOINSTITUCIONES { get; set; }
        public string VC_RESULTADOOBTENIDO { get; set; }
        public string VC_DESCRIPCIONDOCUMENTOFUENTE { get; set; }
        public string VC_INFORMACIONDESEADA { get; set; }
    }
}
